# Generated by Django 5.1.5 on 2025-02-10 14:07

import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='pictures/'),
        ),
    ]
