# Generated by Django 5.1.5 on 2025-05-08 20:59

import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_range', models.CharField(max_length=50)),
                ('image', models.ImageField(storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='activities/')),
                ('highlight_text', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
