# Generated by Django 5.1.5 on 2025-05-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='highlight_text',
        ),
        migrations.AddField(
            model_name='activity',
            name='highlight_words',
            field=models.CharField(blank=True, help_text='Comma-separated list of words to highlight in the description', max_length=255),
        ),
    ]
