# Generated by Django 5.1.5 on 2025-05-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_activity_highlight_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['order', '-created_at'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='activity',
            name='order',
            field=models.IntegerField(default=0, help_text='Order in which this activity appears (lower numbers appear first)'),
        ),
    ]
